# Generated by Django 3.2.25 on 2026-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=7)),
                ('city', models.CharField(default='', max_length=30)),
                ('profile_pic', models.ImageField(upload_to='member/profile/')),
                ('address', models.TextField()),
            ],
        ),
    ]
