# Generated by Django 3.2.25 on 2026-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
