# Generated by Django 3.2.25 on 2026-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50, verbose_name=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')])),
                ('duration_weeks', models.IntegerField()),
                ('session_time', models.IntegerField(help_text='Workout duration in minutes')),
                ('description', models.TextField()),
            ],
        ),
    ]
