# Generated by Django 3.2.25 on 2026-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0006_workoutprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='difficulty_level',
            field=models.CharField(max_length=50),
        ),
    ]
