# Generated by Django 3.2.25 on 2026-03-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0007_alter_workoutprogram_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogram',
            name='difficulty_level',
        ),
    ]
