# Generated by Django 3.2.25 on 2026-03-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0008_remove_workoutprogram_difficulty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
