# Generated by Django 3.2.25 on 2026-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0009_membership_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='membership_plan',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
