# Generated by Django 3.2.25 on 2026-03-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0010_auto_20260316_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('status', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfit_app.member')),
                ('plan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfit_app.membership_plan')),
            ],
        ),
    ]
