# Generated by Django 3.2.25 on 2026-03-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0012_auto_20260323_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='plan_name',
            new_name='plan',
        ),
    ]
