# Generated by Django 6.0 on 2026-04-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0013_rename_plan_name_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='smartfit_app.trainer'),
        ),
        migrations.AddField(
            model_name='member',
            name='request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('assigned', 'Assigned')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='trainer_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upi',
            name='upi_id',
            field=models.CharField(max_length=40),
        ),
    ]
