# Generated by Django 6.0.2 on 2026-04-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0014_member_assigned_trainer_member_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.DeleteModel(
            name='Membership_Plan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
