# Generated by Django 6.0.2 on 2026-04-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfit_app', '0015_remove_payment_plan_remove_payment_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='false', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfit_app.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfit_app.membership_plan')),
            ],
        ),
    ]
